.zappr.yaml

Add .zappr.yaml config

---

README.md

Use `zalando-incubator` instead of `mikkeloscar`.

Update travis badge to point to the right repo

---

CONTRIBUTORS.md

Signed-off-by: Arjun Naik <arjun.naik@zalando.de>
> Issue : #1 
The repository must conform with zalando's OSS guidelines and all files seem to be in order other than the contributors file.

Removed contributors placeholder.

---

Makefile
docs/deployment.yaml
go.mod
main.go
pkg/provider/hpa.go
pkg/provider/metric_store.go
pkg/server/start.go

Rename module path from mikkeloscar -> zalando-incubator

---

pkg/provider/hpa.go
pkg/server/start.go

Adds a prometheus endpoint serving basic Go metrics.

Expose basic go metrics via prometheus

---

pkg/provider/hpa.go
pkg/provider/metric_store.go
pkg/provider/metrics_store_test.go

> Issue : https://github.com/zalando-incubator/kube-metrics-adapter/issues/6
Adding unit tests for `metric_store.go`
- https://github.com/zalando-incubator/kube-metrics-adapter/issues/6

Adding Unit tests to metric_store.go

---

README.md

Some aspects of using the prometheus collector are vague and I've added some clarification for it.

Added clarification of dummy-pod

---

pkg/collector/pod_collector.go
pkg/provider/metric_store.go

Fixed metric labels so that metric are tagged correct. Also added nil check.

Fixed metric labels so that metric are tagged correct

---

delivery.yaml

Add build cache for CDP build

---

.golangci.yml

Added golangci linter

---

pkg/collector/max_collector.go
pkg/collector/max_collector_test.go
pkg/collector/prometheus_collector.go

PR #47 has faulty logic. All errors including ones where the _metrics-adpater_ cannot connect to _prometheus_ are ignored. Only invalid results should be so if there is a connection error then there is no result computed.

Max collector should ignore only no result errors

---

.travis.yml
Makefile
example/main.go
pkg/annotations/parser.go
pkg/annotations/parser_test.go
pkg/collector/json_path_collector.go
pkg/collector/pod_collector.go
pkg/collector/skipper_collector.go
pkg/collector/skipper_collector_test.go
pkg/provider/metrics_store_test.go
pkg/zmon/zmon_test.go

Fixed all errors from the `golangci-lint` command

Fix all errors from golangci-lint command

---

README.md

adds documentation requested by a user
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

add AWS IAM policy as requirement to integrate with AWS SQS

---

pkg/collector/skipper_collector.go
pkg/collector/skipper_collector_test.go

In #70 we changed the logic slightly to essentially require a backend name for stacks with traffic switching, but didn't return an error. This doesn't allow the users notice that their HPAs are misconfigured, they just don't work. Fix by correctly returning an error.

When traffic switching is used, require a backend for the RPS metric

---

pkg/collector/json_path_collector.go

Fix variable name typo

---

.travis.yml
Makefile

Only updating the golangci version

Updating golangci

---

go.mod
go.sum

Update AWS SDK to support AWS IAM solution
Fix #105

Update AWS SDK to support AWS IAM solution

---

.travis.yml

Update Travis to Go 1.14

---

Dockerfile

Use LABEL instead of deprecated `MAINTAINER` keyword.

Use non-deprecated Dockerfile syntax

---

README.md

Documents the interval config clearly!
Fix #296

Clearly document interval config

---

pkg/apis/zalando.org/v1/types.go
pkg/collector/scaling_schedule_collector.go

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

fix typo Saturday

---

Dockerfile
Makefile
delivery.yaml

Build multi-arch image

---

pkg/collector/scaling_schedule_collector.go
pkg/collector/scaling_schedule_collector_test.go

Fix nil pointer dereference when checking if an end date is set for a OneTime Schedule. Also add a test to check for an incorrect end date format.

Fix nil pointer dereference

---

go.mod
go.sum

Update dependencies as indicated by @dependabot

Update dependencies 2023-01-02

---

.github/workflows/ci.yaml
.github/workflows/release-chart.yml

added chart release workflow

---

docs/deployment.yaml
example/Dockerfile

Use image hosted on ghcr.io in docs example

Use ghcr.io in example

---

example/deploy/hpa.yaml

Signed-off-by: Dilina <macowtdy@gmail.com>
Keep the example up-to-date
Update apiVersion for autoscaling from v2beta1 to v2

change apiVersion for k8s autoscaling

---

README.md

update Readme.md, for adding kubernetes installation
Signed-off-by: John Zheng<john.zheng@hp.com>
Currently, no introduction for k8s installation. 
It bring confuse, especially for starter.
A few sentences describing the overall goals of the pull request's
commits.
- Configuration change
- Documentation / non-code
These should highlight any db migrations, feature toggles, etc.

Update README.md -- add kubernetes installation

---

Dockerfile
delivery.yaml

Use static base image instead of alpine.

Use static base image

---

docs/helm/Chart.yaml
docs/helm/values.yaml

Update the chart to use the latest version v0.2.3
Fix #727

Update chart to v0.2.3

---

docs/helm/templates/service-account.yaml
docs/helm/values.yaml

Add option service account annotation
> Issue : #776 (only if appropriate)
None

776: add serviceAccountAnnotations
