zalando-incubator/kube-metrics-adapter

README.md
The build was registered at travis-ci.org not .com.
=> travis-ci.org instead of travis-ci.com

pkg/collector/collector.go
Signed-off-by: Arjun Naik <arjun.rn@gmail.com>
The adapter attempts to collect metrics for `Resource` type and then records warnings in the HPAs. This should prevent that.
=> Skipper metrics collection for resource types

docs/rbac.yaml
Update RBAC configuration to reflect what is working: https://github.com/zalando-incubator/kubernetes-on-aws/pull/1598
Fix #17
=> Fix RBAC configuration

.gitignore, .travis.yml, pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go
In cases where replicas take a bit of time to get ready, the Stackset Controller just keeps on scaling. To avoid this issue, using the total replicas instead of replicas that are ready.
=> Look at total replicas instead of readyReplicas

pkg/zmon/zmon.go
Fix json serialization naming for zmon queries
When querying zmon/KairosDB aggregators did not work since json field name was wrong. 
Therefore multi-entity queries used to get only last values. This PR aims to fix it
=> Fix json serialization naming for zmon queries

README.md, pkg/collector/max_collector.go, pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go, pkg/server/start.go
The backend weights for skipper ingress are stored as annotations in the ingress object. These are used to weight the returned metrics. Also the `request-per-second` metric name also contains the backend name.
- Weighting of RPS metrics
- Bug fix for when the MaxCollector gets only zero values
=> Added weighting of RPS metrics based on backend weights

README.md, pkg/collector/skipper_collector.go
Looks like slashes are not supported.
=> Changed request-per-second metric separator to a comma

pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go
The case when the backend weight was zero was not handled and it was falling back to the logic when the weight is not set. This PR addresses that issue and adds a corresponding test.
=> Added missing logic and test case when weight of backend is 0

pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go
When the backend is not specified in the metric name the weight is defaults to zero. It should instead be 1 otherwise the `request-per-second` metric is useless.
=> Fix case when backend is not set

pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go
The case when the backend weight is present only in one of the ingress annotations was not handled which caused the backend weight to be calculated as 1. 
=> Handle condition when backend weights only sometimes present

how-to/skipper_setup.md
This PR contains instructions to configure Promtheus and kube-metrics-adapter for metrics collection of skipper metrics. Addresses issue #30
=> Added instructions on configuring adapter to collect ingress metrics

pkg/collector/collector.go
The annotation config parser was not initialized correctly.
=> Fix nil dereference panics for the Annotation config parser

pkg/collector/collector.go
In a previous PR #39 [in this file](https://github.com/zalando-incubator/kube-metrics-adapter/pull/39/files#diff-82aaae0c6d8f8f72eeab56f04830af24) while refactoring some code I dropped the code which copies external metric configs into the collector. I've re-added.
=> Add the labels from the zmon check into the config object

pkg/collector/collector.go, pkg/collector/zmon_collector.go, pkg/collector/zmon_collector_test.go
This fixes an issue of setting up a ZMON collector where the incorrect
key `Configuration` was used, which was not initialized in the metrics
config parser. The `Config` key is the right one to use.
=> Remove unused Configuration key from MetricConfig

pkg/collector/max_collector.go, pkg/collector/max_collector_test.go
The `MaxCollector` fails when even one of the metrics collector returns an error. But when other metrics are present it should just continue and return the max of the rest.
=> Return a value when atleast one of the metrics returns a value

pkg/provider/hpa.go, pkg/provider/hpa_test.go
This fixes an issue where collectors would be leaking when HPAs are
getting updated.
Fix this by stopping the collector started for the previous version of
the HPA.
=> Prevent leaking collectors when HPA gets updated

README.md, pkg/collector/prometheus_collector.go, pkg/server/start.go
Allows specifying Prometheus based metrics as `External` target.
I'm not 100% sure on the format for the annotation. Feedback welcome.
Fix #45
/cc @timstoop
=> Allow Prometheus metrics for External target

README.md, pkg/annotations/parser_test.go
> Issue : #62 
The pod collector can use HTTPS to scrape metrics but this is not documented currently
=> Document how to use HTTPS for pod collector

pkg/provider/metric_store.go, pkg/provider/metrics_store_test.go
Fixes the response from `GetMetricsBySelector` in case no metrics are
found. This issue caused a panic in kube-controller-manager:
https://github.com/kubernetes/kubernetes/pull/80392
Fix #40
=> Fix response on no metrics found

delivery.yaml
In preparation for cutting the first release we need to correctly tag docker images in our build pipeline.
=> Use proper tags for docker images

pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go
Backends with zero weights are completely missing from the traffic weight annotations. This currently triggers the fallback logic in the adapter and they're treated as backends that receive 100% of the traffic, causing massive scale ups. Fix by explicitly checking if we've found any of the annotations instead.
=> RPS: Correctly handle backends not present in the annotations

pkg/collector/skipper_collector_test.go
We want to check that there are no annotations on the ingress, not in the configuration.
=> Skipper: fix the no annotation test so it makes more sense

README.md, pkg/collector/prometheus_collector.go
> Issue : #74 
In this PR I've added an option to specify a Prometheus URL in an API annotation, so it will override the one specified in CLI arguments. 
- New feature
None
None
None
=> collector/prometheus: add Prometheus URL (optional) as an annotation in HPA

pkg/collector/aws_collector.go, pkg/collector/collector.go, pkg/collector/prometheus_collector.go, pkg/collector/zmon_collector.go, pkg/collector/zmon_collector_test.go
This is a slight refactoring/unification of how metric
labels/annotations are parsed and handled across collectors. This is
done to prevent crashes when labels are not defined on external metrics.
Some collectors allow annotations to overwrite labels. This is moved to the parsing part instead of handling it in each collector.
Fix #69
=> Prevent panic when parsing HPAs

delivery.yaml, go.mod
* Fail on dirty repositories
* Fail if we don't have a version tag on `master`
=> Fail on dirty and/or non-exact versions on master

README.md, example/deploy/hpa.yaml, pkg/collector/collector.go, pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go
This adds support for `averageValue` for the `request-per-second` metric based on Ingress Objects. This is only supported from Kubernetes `>=v1.14` (https://github.com/kubernetes/kubernetes/pull/72872).
When defining the HPA with `autoscaling/v2beta1` you still need to define `targetValue` even though it won't be used when `averageValue` is set. Once we default to `autoscaling/v2beta2` this akward API will be gone.
This PR also enhances the README with Kubernetes compatibility expectations and a reference to supported Kubernetes versions for each collector type.
=> Add support for averageValue for request-per-second Skipper metric

README.md, pkg/collector/json_path_collector.go, pkg/collector/json_path_collector_test.go
This is the initial implementation of support for JSONPath expressions that return arrays of values instead of a single value.
This is the initial implementation of support for JSONPath expressions that return arrays of values instead of a single value.
This extends the collector to define a few handy reducer functions that take in the slice of float64 and return a single value. It also allows the user to define which reducer function to use via the `metric-config.<metricType>.<metricName>.json-path/reducer-func` annotation, which can have the values of 'avg', 'min', 'max' and 'sum'.
For instance, the Ruby puma webserver exposes metrics of the form of `$.worker_status[*].last_status.pool_capacity` that have to be consumed as an array of values to be properly targetted.
- New feature …
=> Support for JSONPath expressions that return arrays of values

pkg/collector/json_path_collector.go, pkg/collector/json_path_collector_test.go
Fixes type switch on JSONPath collector to actually run code related to slices of values (to be aggregated).
This fixes an issue with the type switch that was never able to fall into cases of []<number>, being <number> a number type such as int, float32, float64. This is because Go can't type cast slices of interface{} out right because it's impossible to know the true types of the slice members beforehand.
NA
NA
=> Fix type switch on JSONPath collector

pkg/collector/collector.go
Signed-off-by: Johann Fuechsl <johann@fuechsl.co>
> Issue : #89 
Perform a copy of the MatchLabels map to the Config field of the metric config object for external metrics.
None
=> Fix #89 by copying the MatchLabels map instead of referencing it.

pkg/collector/collector.go, pkg/provider/hpa.go, pkg/provider/hpa_test.go, pkg/server/start.go
Permit disregarding incompatible HPAs.
> Issue : #94
This adds a `--disregard-incompatible-hpas` that makes the HPA provider stop erroring out when a collector cannot be created for a metric in a HPA. Useful when kube-metrics-adapter runs alongside another metrics provider. Fixes issue #94.
- Configuration change
NA. The flag should assume the sensible Go zero value default of `false`.
=> Permit disregarding incompatible HPAs

main.go, pkg/collector/json_path_collector.go, pkg/collector/json_path_collector_test.go, pkg/collector/pod_collector.go
Currently a new `http.Client` is created whenever a pod metrics endpoint has to be scraped. This leaves idle connections lying around which piles up and causes a memory leak. By reusing the client and setting idle connection timeouts we can prevent this.
=> Reuse the HTTP client for scraping pods

pkg/provider/hpa_test.go
A previous PR #95 introduced some changes with the old `autoscaling/v2beta1` api which was merged after the version upgrade from #101 
This PR fixes the broken build and tests.
=> Updated the tests

README.md, pkg/collector/influxdb_collector.go, pkg/collector/influxdb_collector_test.go, pkg/server/start.go
Fix an error in passing parameters to InfluxDBCollector and convert to `org` instead of `orgID` (that's actually how InfluxDB treats that param, it could be the org name or ID).
Fixing that error would make it work 😅 
- Documentation / non-code
=> fix(influxdb): fix swap of org/token

README.md, pkg/collector/json_path_collector.go, pkg/collector/json_path_collector_test.go
Add support for passing URL query params to pod metric endpoints
Issue : #108 
Adds a new metric-config option named `raw-query`. The value of this option will be appended to the metric `path` as URL query parameters to be used by the pod's application.
E.g.,:
```
metric-config.pods.requests-per-second.json-path/raw-query: "foo=bar&baz=bop"
```
will append `?foo=bar&baz=bop` to the URL.
New feature (non-breaking change which adds functionality)
=> Add support for passing URL query params to pod metric endpoints

pkg/collector/json_path_collector.go
Error contains twice the namespace instead of name of the pod and namespace
> Issue : #1234 (only if appropriate)
fix
- Documentation / non-code
=> fix error to not contain twice the namespace

go.sum, pkg/collector/pod_collector.go, pkg/collector/pod_collector_test.go
Fetch metrics from pods in parallel
Fetching metrics from pods sequentially, with a large number of
pods, can result in poor performance when some of those pods have
been terminated by the HPA in a normal scale down event.
E.g., imagine the following sequence of events:
* kube-metrics-adapter retrieves a list of 30 pods to query for metrics
* HPA scales down to 20 pods
* kube-metrics-adapter attempts to retrieve metric from pod that is terminating/terminated, times out after 15 seconds
* 15 second timeout for other 9 terminating/terminated pods
2.5 minutes spent retrieving metrics
=> Fetch pod metrics in parallel

README.md, go.sum, pkg/collector/httpmetrics/json_path.go, pkg/collector/httpmetrics/pod_metrics.go, pkg/collector/httpmetrics/pod_metrics_test.go
Custom request and connect timeouts
Allows per metric configuration of connect and request timeouts, when querying pods for JSON metrics. Somewhat related to #152, a 15 second timeout is quite long for a healthy production environment ;)
=> Add support for custom timeouts

pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go, pkg/provider/metric_store.go
This adds support for ingresses under `networking.k8s.io/v1beta1` such that there is a migration path for ingresses currently under `extensions/v1beta1` for metrics relying on the skipper collector.
It also changes the read api for ingresses to use `networking.k8s.io/v1beta1` this is available since Kubernetes v1.14 which is already the minimum version supported for the skipper collector.
=> Add support for Ingress of API Group networking.k8s.io

pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go
The value of `zalado.org/backend-weights` annotation on an ingress is defined as `map[string]float64` in most places e.g skipper and stackset-controller. 
Before we parsed it as `map[string]int` which would not work if a weight was defined e.g. as `100.0` as it would result in the following error: `json: cannot unmarshal number 100.0 into Go value of type int`.
For most cases this was actually not a problem as we mostly use whole numbers and go will marshal a `float64` like `100.0` into the string representation `100` which can be unmarshaled into an `int`.
However for some ingresses the values are represented as `100.0` and this would fail.
* This changes both the type from `int` -> `float64` and properly handles any json parsing errors so such issues wouldn't be swallowed without a …
=> Correctly treat ingress weight values as float64

README.md, go.mod, go.sum, pkg/collector/http_collector.go, pkg/collector/httpmetrics/json_path.go, pkg/collector/httpmetrics/json_path_test.go, pkg/collector/httpmetrics/pod_metrics.go, pkg/collector/httpmetrics/pod_metrics_test.go
This changes the jsonPath library used internally to a new one (https://github.com/spyzhov/ajson) which supports bracket notation for `jsonPath`. e.g. you can now ALSO use something like `$['my.metric.key']`. Before the metric key could not have dots inside as only the dot notation was supported.
Fix #91
=> Support bracket notation in jsonPath

pkg/collector/httpmetrics/json_path.go, pkg/collector/httpmetrics/json_path_test.go
Follow up to #192 fix handling of a json response where the jsonPath doesn't result in an Array or Number. I.e. the jsonPath is misconfigured or the response is unexpected format.
Prevents the controller from crashing with:
```
panic: runtime error: index out of range [0] with length 0
```
=> Fix handling of invalid/empty json response

go.mod, go.sum, pkg/server/start.go
This replaces the `custom-metrics-apiserver` dependency with a temporary fork that includes this currently unmerged PR: https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/65
This enables the metrics-adapter to expose OpenAPI spec and thus removes the apiserver logs:
```
loading OpenAPI spec for "v1beta1.external.metrics.k8s.io" failed with: OpenAPI spec does not exist'
```
The idea is to revert back to the main version as soon as the upstream PR is merged.
Fix #99
=> Use OpenAPI spec fork

go.mod, go.sum
Follow up to #164
Switch back to the upstream version which now has the OpenAPI spec fixes included: https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/65
=> Use upstream version of custom-metrics-apiserver

README.md
There is a way to configure scrape interval.
> Issue : https://github.com/zalando-incubator/kube-metrics-adapter/issues/214 (only if appropriate)
=> Documenting scrape interval

README.md, example/deploy/hpa.yaml, pkg/annotations/parser.go, pkg/collector/collector.go, pkg/collector/collector_test.go, pkg/collector/http_collector.go, pkg/collector/influxdb_collector.go, pkg/collector/influxdb_collector_test.go, pkg/collector/pod_collector.go, pkg/collector/pod_collector_test.go, pkg/collector/prometheus_collector.go, pkg/collector/zmon_collector.go, pkg/collector/zmon_collector_test.go, pkg/server/start.go
For historical reasons (i.e. use of previous autoscaling API versions) we have been mapping **metric names** to the different collector types. I.e. if you wanted a metric based on `prometheus` you would name the metric `prometheus-query`.
This design has the downside that multiple metrics will have the same name and it becomes hard to distinguish as reported in #104 
In some cases it can even prevent having more than a single metric of a certain type i.e. if you use the `zmon-check` metric and have the same `check-id` but different complex keys defined (complex keys must be defined as annotation, and this will overlap if you have more than a single zmon-check metric defined).
It was initially done because we didn't have any other identifiers in the HPA spec, at least for custom metrics, …
=> Use labels for mapping metric types to metrics

pkg/collector/prometheus_collector.go, pkg/collector/prometheus_collector_test.go
Follow up to #81 
This fixes the mapping of query defined in the annotation to the prometheus metric when using the new configuration style where metric type is defined as `type: prometheus`.
Adds test to cover the initialization of external prometheus metric types which was previously not covered.
Fix #227
=> Fix mapping of Prometheus query for new metric configuration

pkg/server/start.go
NewSession is being deprecated, NewSessionWithConfig handles things
such as role arns. This fixes permissions issues for users using
role arns for service accounts.
Updated to use the suggested session constructor for AWS sessions. Which fixes certain AWS config values not being read at run time.
We noticed our HPA's were failing to scale on SQS message length metrics, on closer inspect the metrics adapter wasn't picking up our service accounts IAM_ROLE. This was because the sessions were being instantiated using `NewSession` which for whatever reason doesn't pick up role arn automatically. It's suggested by AWS to use the new `NewSessionWithConfig` constructor instead, which attempts to load configurations from multiple sources. See: https://github.com/aws/aws-sdk-go/issues/3101 
_What …
=> UPDATED to use NewSessionWithConfig instead of NewSession

Dockerfile
Use compliant base image according to our tech rules of play:
- KDP-1: use an approved Docker base image and version from the list of
allowed Docker Base Images under the pierone namespace ‘library’.
=> Switch to compliant base image

pkg/collector/aws_collector.go
Fixes an issue where the AWS SQS collector could not be correctly setup when the metric name was anything but `sqs-queue-length` even though it should be possible since #219
Removes the unneeded/invalid check from the AWS collector initialization.
Fix #239
=> Don't check for metric name on AWS init

docs/helm/templates/rbac.yaml
> Issue : #252
The incident reported in #252 occurs because cluster role bindings use wrong namespace for `horizontal-pod-autoscaler` service account. They get the namespace from `{{ .Values.namespace }}` expression which has a value other than `kube-system`.
This PR fixes that issue by setting the namespace for `horizontal-pod-autoscaler` service account as `kube-system`.
Steps provided in #252 can be used to test this issue.
=> Fix the namespace of horizontal-pod-autoscaler service account used in the helm chart

pkg/collector/aws_collector.go, pkg/collector/collector.go, pkg/collector/http_collector.go, pkg/collector/http_collector_test.go, pkg/collector/influxdb_collector.go, pkg/collector/influxdb_collector_test.go, pkg/collector/pod_collector.go, pkg/collector/prometheus_collector.go, pkg/collector/zmon_collector.go, pkg/collector/zmon_collector_test.go, pkg/provider/hpa.go, pkg/provider/metric_store.go, pkg/provider/metrics_store_test.go
This introduces namespacing of external metrics such that metrics from two different namespaces with the same configuration (name/labels) don't overlap.
This is done by:
1. Changing the metric store to index by namespace
2. Adding namespace when setting up a collector and pass namespace via the CollectedMetric.
Fix #255
=> Namespace external metrics

pkg/provider/hpa.go, pkg/provider/hpa_test.go, pkg/server/start.go
Signed-off-by: Harman Singh <iamgrewal7@gmail.com>
add commandline flags to set GC interval and metrics TTL
> Issue : #97  (only if appropriate)
These should highlight any db migrations, feature toggles, etc.
=> add commandline flags to set GC interval and metrics TTL

docs/custom-metrics-apiservice.yaml, docs/external-metrics-apiservice.yaml, docs/helm/templates/custom-metrics-apiservice.yaml, docs/helm/templates/external-metrics-apiservice.yaml
When installing this adapter into Kubernetes v1.19+, you will receive the following deprecation notice:
```
W0426 10:49:35.932780     318 warnings.go:70] apiregistration.k8s.io/v1beta1 APIService is deprecated in v1.19+, unavailable in v1.22+; use apiregistration.k8s.io/v1 APIService
```
This migration was described by the [KubernetesDeprecation Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#apiservice-v122) as one with "No notable changes", so there should be no functionality change.
Should be deployed before Kubernetes v1.22.
=> Updated apiservice to v1

docs/helm/Chart.yaml, docs/helm/values.yaml
> Issue : #257
Partially addresses #257 where prometheus external was not functioning. Unlike 0.1.9, this version does have working external Prometheus metrics and my local testing indicates that using 0.1.10 works normally!
- Bug fix through version bump
=> Bump to v0.1.10 for helm

pkg/apis/zalando.org/v1/types.go, pkg/client/clientset/versioned/typed/zalando.org/v1/clusterscalingschedule.go, pkg/client/clientset/versioned/typed/zalando.org/v1/fake/fake_clusterscalingschedule.go, pkg/client/clientset/versioned/typed/zalando.org/v1/fake/fake_zalando.org_client.go, pkg/client/clientset/versioned/typed/zalando.org/v1/zalando.org_client.go, pkg/client/informers/externalversions/zalando.org/v1/clusterscalingschedule.go, pkg/client/informers/externalversions/zalando.org/v1/interface.go, pkg/client/listers/zalando.org/v1/clusterscalingschedule.go, pkg/client/listers/zalando.org/v1/expansion_generated.go
During #284 we set the ClusterScalingSchedule scope as `Cluster` but
just for kubebuilder. This flag has no effect in the generated clients.
It means the generated clients expect a namespace argument when handling
ClusterScalingSchedule resources. It works fine to list all of the
resources but makes it impossible to request a specific resource
defining its name.
This commit sets the `+genclient:nonNamespaced` flag for the CRD and
adds the regenerated clients. It does not affect any of the usages of the
clients in this codebase so far.
Also discussed [here](https://github.com/zalando-incubator/kube-metrics-adapter/pull/315#issuecomment-845825438).
=> Remove ClusterScalingSchedule clients namespace

pkg/collector/collector.go
`ContainerResource` type metrics are supported as alpha feature in Kubernetes v1.20. They are implemented in the in-tree HPA, so we don't need/want to support them here similar to how we don't support `Resource` type metrics.
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#container-resource-metrics
=> Ignore ContainerResource metrics

README.md, pkg/collector/http_collector.go, pkg/collector/http_collector_test.go
This commit removes the logic that checks for an identifier label in the
http collector config. It also removes the documentation on the README
that mentions that the metric has to be in an old format, removed in
the #219.
Fixes #331
Signed-off-by: Jonathan Juares Beber <jonathanbeber@gmail.com>
=> Remove HTTP collector check on identifier label

README.md, pkg/zmon/zmon.go, pkg/zmon/zmon_test.go
- only add group_by "key" if the key is provided
- remove deprecated aggregators "dev" and "first"
- add X-Attribution header for query attribution
- tests
This PR is mainly @pitr work and some tests. It's similar to #347 but I don't know how to push changes in a forked branch for some reason.
=> fixes for ZMON client

README.md, pkg/collector/collector.go, pkg/collector/skipper_collector.go
When users wanted to scaled based on the RPS of a single backend for a traffic weighted Ingress/RouteGroup they could define the backend name as part of the metric name e.g. `requests-per-second,<backend>`. This "hack" of making the backend part of the metric name was introduced back when we used `autoscaling/v2beta1` when labels were not supported on Object type metrics.
Switch to use the match labels for defining the `backend` which is possible with `autoscaling/v2beta2`.
```yaml
metric:
name: requests-per-second
selector:
matchLabels:
backend: backend1 # optional backend
```
The previous deprecated format looked like this:
```yaml
metric:
name: requests-per-second,backend1
```
=> Use labels for specifying Ingress/RouteGroup backend

pkg/collector/scaling_schedule_collector.go, pkg/collector/scaling_schedule_collector_test.go
The HPA has a feature to do not scale up and down when the change in the
metric is less than 10%:
> We'll skip scaling if the ratio is sufficiently close to 1.0 (within a
> globally-configurable tolerance, from the
> `--horizontal-pod-autoscaler-tolerance` flag, which defaults to 0.1.
It could lead to pods scaling up to 10% less than the target for
ScalingSchedules and then not scaling to the actual value if the metric
calculated before was less than 10% of the target.
This commit uses 10 fixed buckets for scaling, this way we know the
metric returned during a scaling event is at least 10% more than a
previous one calculated during the period of ramp-up. The same is valid
for the scaling down during a ramp-down
=> Use 10 buckets on ScalingSchedule ramp-up/down

pkg/provider/hpa.go, pkg/provider/metric_store.go, pkg/provider/metrics_store_test.go
The current implementation of the metrics store for custom metrics uses
just the object name as key. When scenarios where two HPAs reference the
same object but have different metric calculation (e.g. ingresses with
different weights), kube-metrics-adapter calculates the two metrics but
always overrides one of the metrics when saving it to the store.
This commit implements the use of a labels hash in the custom metrics
store. This way, metrics are identified not just by the referenced
object, but also by its selectors.
The metrics store, both the custom and external one, make heavy usage of
maps of strings to strings. This leads to a presumable confusing or at
least hard to read codebase.
This commit tries to increase readability and maintainability of the
metric stores by using custom …
=> Use labels hash in the custom metrics store and metrics store :nail_care: 

README.md, docs/helm/templates/rbac.yaml, docs/rbac.yaml, example/deploy/hpa.yaml, example/deploy/ingress.yaml, pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go, pkg/provider/metric_store.go, pkg/provider/metric_store_test.go
Given the deprecation of `extensions/v1beta1`, remove it from Ingress possibilities.
=> Limit ingress support to only networking.k8s.io/v1

docs/cluster_scaling_schedules_crd.yaml, docs/scaling_schedules_crd.yaml, pkg/apis/zalando.org/v1/types.go, pkg/apis/zalando.org/v1/zz_generated.deepcopy.go, pkg/collector/scaling_schedule_collector.go, pkg/collector/scaling_schedule_collector_test.go
The added end time/date options adds greater flexibility for (cluster) scaling schedules as this offers an alternative to the current start time/date + duration (in minutes) configuration - which is not easily readable when longer durations are present. The end time/date is an optional field which will only override the schedule duration if it is further in the future. Likewise, the duration field will override the scheduled end date if it is set to end after the scheduled end date. In short: the latest ending time/date will be given priority.
=> Update scalingschedule config

README.md, pkg/annotations/parser.go, pkg/annotations/parser_test.go, pkg/collector/aws_collector.go, pkg/collector/collector.go, pkg/collector/collector_test.go, pkg/collector/http_collector.go, pkg/collector/http_collector_test.go, pkg/collector/influxdb_collector.go, pkg/collector/influxdb_collector_test.go, pkg/collector/pod_collector.go, pkg/collector/pod_collector_test.go, pkg/collector/prometheus_collector.go, pkg/collector/prometheus_collector_test.go, pkg/collector/scaling_schedule_collector.go, pkg/collector/scaling_schedule_collector_test.go, pkg/collector/skipper_collector.go, pkg/collector/skipper_collector_test.go, pkg/collector/zmon_collector.go, pkg/collector/zmon_collector_test.go, pkg/provider/hpa.go, pkg/provider/hpa_test.go, pkg/provider/metric_store.go, pkg/provider/metric_store_test.go
Switch from `autoscaling/v2beta2` to `autoscaling/v2` for HPA
Issue : #550
`autoscaling/v2beta2` apiVersion is removed from Kubernetes v1.26. We need to switch from `autoscaling/v2beta2` to `autoscaling/v2` in order to be able to run it. Application's log:
```
W0426 10:15:41.107525       1 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
```
Both apiVersions are available in the currently used lib v1.23, so no dependencies updates are required.
This will bump the minimal supported version of Kubernetes to v1.23.
_List of tasks you will do to complete the …
=> Update HPA to autoscaling/v2 apiVersion

docs/helm/Chart.yaml, docs/helm/templates/cluster_scaling_schedules_crd.yaml, docs/helm/templates/deployment.yaml, docs/helm/templates/rbac.yaml, docs/helm/templates/scaling_schedules_crd.yaml, docs/helm/values.yaml
Bump helm chart app version to v0.2.0
- Bumps helm chart image version to v0.2.0
- Syncs CRD and RBAC changes from `docs/` to helm chart
- Configuration change
=> helm: bump app version to v0.2.0

CONTRIBUTING.md, README.md, docs/cluster_scaling_schedules_crd.yaml, docs/helm/templates/cluster_scaling_schedules_crd.yaml, docs/helm/templates/scaling_schedules_crd.yaml, docs/scaling_schedules_crd.yaml, pkg/apis/zalando.org/v1/types.go, pkg/collector/skipper_collector_test.go, pkg/provider/hpa.go, pkg/server/start.go
```
codespell --skip .git | less
```
See https://github.com/codespell-project/codespell
=> all: fix typos discovered by codespell

.golangci.yml, pkg/collector/external_rps_collector.go
Update golangci-lint config. Remove legacy `deadcode` and `varcheck` linters.
Also fix formatting of one file.
=> Update golangci-lint config

.github/workflows/gh-packages.yaml
Adds github action for pushing multi-arch image to `ghcr.io/zalando-incubator/kube-metrics-adapter:<tag>` whenever a tag is created.
Fix #596
=> Setup multi-arch container build to ghcr

.github/workflows/gh-packages.yaml
This adds a step to push a `:latest` tag to ghcr.io on every merge to master.
It also changes the push with tag to only trigger when there is a tag created.
Fix #624
=> Enable pushing to ghcr.io on merge to master

README.md, pkg/collector/nakadi_collector.go, pkg/nakadi/nakadi.go, pkg/nakadi/nakadi_test.go, pkg/server/start.go
This adds support for scaling based on Nakadi subscriptions by utilizing the nakadi stats api: https://nakadi.io/manual.html#/subscriptions/subscription_id/stats_get
It's possible to define an HPA like below:
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
name: myapp-hpa
annotations:
metric-config.external.my-nakadi-consumer.nakadi/interval: "60s" # optional
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: custom-metrics-consumer
minReplicas: 0
maxReplicas: 8 # should match number of partitions for the event type
metrics:
- type: External
external:
metric:
name: my-nakadi-consumer
selector:
matchLabels:
type: nakadi
subscription-id: "708095f6-cece-4d02-840e-ee488d710b29"
metric-type: "consumer-lag-seconds|unconsumed-events"
target:
value: "600" …
```
=> Add support for scaling based on Nakadi

README.md
Somehow the committed suggestion in #636 ended up creating the table rows twice. This fixes it.
This also fixes a mistake in the example for Nakadi where `type: Value` was missing.
=> Fix table for nakadi docs

README.md
Fix typo in the documentation that might mislead users and not properly configure the metric.
A few sentences describing the overall goals of the pull request's
commits.
- Documentation / non-code
=> Fix typo on metric annotation for external RPS metric

docs/helm/Chart.yaml, docs/helm/templates/cluster_scaling_schedules_crd.yaml, docs/helm/templates/scaling_schedules_crd.yaml, docs/helm/values.yaml
Current chart is old and not work, I change the code based on the latest version, latest installation files under /docs.
I test and it works well.
Pls review, thanks.
> Issue : #727  
A few sentences describing the overall goals of the pull request's
commits.
Note:
Current helm charts does not work ./docs/helm
You can install it successfully, but never work.
If you run `cd docs; kubectl apply -f .`, it can work.
If you view current helm charts,
- The version is old.
- The values are not expected.
- Even some status inside template .
It may not professional enough for such a good product.
BTW, feel free to modify if necessary.
- Bug fix (non-breaking …
=> Fix previous helm chart issue for installation

.github/dependabot.yml
Try out grouping dependabot updates
Disabled the schedule for now to test how it work. Ignoring `k8s.io/` packages as we normally update those manually together with kubernetes-on-aws.
ref: https://github.com/dependabot/dependabot-core/issues/7547
=> Group go.mod updates

.github/dependabot.yml
Follow up to #729 the config was invalid without a schedule defined.
=> Group dependabot updates daily

.github/dependabot.yml
daily updates are a bit too spammy, only allow weekly updates.
=> Only let Dependabot update weekly

docs/cluster_scaling_schedules_crd.yaml, docs/scaling_schedules_crd.yaml, go.mod, pkg/apis/zalando.org/v1/types.go, pkg/controller/scheduledscaling/scaler.go, pkg/controller/scheduledscaling/scheduled_scaling.go, pkg/controller/scheduledscaling/scheduled_scaling_test.go, pkg/server/start.go
The Horizontal Pod Autoscaler (in `kube-controller-manager`) has a configuration `--horizontal-pod-autoscaler-tolerance=0.1` which defines how much a metric has to change before the HPA scales. E.g. if a metric is indicating a change that would result in less than 10% (default) change of replicas it won't take any action. This setting is meaningful for e.g. CPU or Memory based scaling where too frequent up and down-scale is not desired.
However, for a more stable metric, like Schedule Scaling, it's undesirable/confusing when it doesn't adjust the scaling when the change is below the tolerance.
Example: Imagine you have configured scheduled scaling to scale to 95 pods. Now the schedule is increased such that it will result in 100 pods. Because this is a 5.3% increase which is less than the …
=> Adjust HPA when schedule scaling change is below tolerance

pkg/controller/scheduledscaling/scheduled_scaling.go, pkg/controller/scheduledscaling/scheduled_scaling_test.go
This is a follow up to #765 
it fixes a bug where the controller would crash if the `AverageValue` was not defined on the user HPA. This is an invalid configuration from the users and should just be ignored.
It adds a test case which fails before the fix.
Example of crash:
```
time="2024-12-13T14:07:00Z" level=info msg="Adjusting scaling"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x885dae]
goroutine 1918 [running]:
k8s.io/apimachinery/pkg/api/resource.(*Quantity).ScaledValue(0x20?, 0x90?)
/go/pkg/mod/k8s.io/apimachinery@v0.31.3/pkg/api/resource/quantity.go:797 +0xe
k8s.io/apimachinery/pkg/api/resource.(*Quantity).MilliValue(0xc000605f40?)
/go/pkg/mod/k8s.io/apimachinery@v0.31.3/pkg/api/resource/quan …
```
=> Fix missing AverageValue on HPA

README.md, pkg/collector/http_collector.go, pkg/collector/httpmetrics/json_path.go, pkg/collector/httpmetrics/json_path_test.go, pkg/collector/httpmetrics/pod_metrics.go, pkg/collector/httpmetrics/pod_metrics_test.go
Implements ajson's scripting engine on Pod collector through a new `json-eval` config key.
> Issue : #781
This allows to do "basic" data massaging before ingestion using the [scripting engine](https://github.com/spyzhov/ajson?tab=readme-ov-file#script-engine). This allows things like arithmetic operations on different keys of the returned document, to calculate, for example, usage percents given idle and total workers.
- Configuration change
`json-key` and `json-eval` are mutually exclusive, this PR adds checks for either of them being present and not …
=> Add support for ajson scripting engine 

docs/cluster_scaling_schedules_crd.yaml, pkg/apis/zalando.org/v1/types.go
Same as https://github.com/zalando-incubator/kubernetes-on-aws/pull/9302
> ClusterScalingSchedule is the only global CRD that is displayed as part of kubectl get all. This is fairly confusing when you want to see "all" resources in a namespace (knowing that all is not really everything) but you constantly also see the ClusterScalingSchedule everytime.
> This was recently introduced by a bug fix but turns out the old (bugged) behaviour was actually better.
=> Remove all category from ClusterScalingSchedule

README.md, pkg/collector/nakadi_collector.go, pkg/nakadi/nakadi.go, pkg/nakadi/nakadi_test.go, pkg/provider/metric_store.go
This extends the nakadi collector to support filtering subscriptions based on fields: `owning-application,event-types,consumer-groups`
```yaml
metrics:
- type: External
external:
metric:
name: my-nakadi-consumer
selector:
matchLabels:
type: nakadi
owning-application: my-app
event-types: event_type_v1,event_type_v2
consumer-group: abcd
metric-type: "consumer-lag-seconds|unconsumed-events"
```
This allows targeting a subscription without knowing the subscription-id.
=> Add support for filtering nakadi subscriptions
